#!/bin/bash

# Debian post-install script for the etrial-manager package. This needs to be
# rewritten so that the custom CA is handled separately. The need to handle
# multiple instances on a single IPv4 address, and obtain multiple certificates
# from Let's Encrypt, changes the design a bit.

if [ ! -f /etc/nginx/client.crt ]; then

  echo "Creating new CA ..."
  openssl ecparam -genkey -name secp256r1 | openssl ec -out /etc/nginx/client.key

  # The server certificate must be stored in /etc/nginx. nginx presents this when
  # users attempt to connect. client.crt is a certificate stored on the server
  # and used for the purpose of HTTPS client authentication.

  subj="/C=AU/ST=NSW/L=Sydney/O=CDPP/CN=etrial"
  echo "Creating new server certificate with subject $subj ..."
  openssl req -new -x509 -days 3650 -subj $subj \
    -key /etc/nginx/client.key -out /etc/nginx/client.crt

  echo "Creating admin.pfx certificate bundle ..."
  /usr/share/etrial-manager/scripts/add-https-user.sh admin "Default Administrator" /root
fi

# Create app user.
adduser etrial --disabled-password --gecos ''
chown etrial:etrial /home/etrial

# Configure WebDAV for each user class.
for user in judge jury witness; do
  mkdir -p /home/etrial/dav/$user
  chown etrial:etrial /home/etrial/dav/$user
  chmod 755 /home/etrial/dav/$user
done
if [ ! -f /etc/nginx/dav.htpasswd ]; then
  # Generate new passwords for WebDAV users.
  touch /etc/nginx/dav.htpasswd
  for user in judge jury witness; do
    pass=$(pwgen -1 -n 12)
    echo "$pass" | htpasswd -i /etc/nginx/dav.htpasswd "$user"
    echo "$user:$pass"
  done > /home/etrial/dav.htpasswd.clear
fi

systemctl daemon-reload
systemctl enable etrial-manager
systemctl stop etrial-manager etrial-davserver@judge etrial-davserver@jury etrial-davserver@witness
systemctl start etrial-manager
systemctl reload nginx
